NguyenH Tien
LlirikOknessu/LinearRegression pull request #10
Opened 2022-11-03 00:42 UTC by ACasualGuyFromDaLat

I did something here with the given data. Please check
- raw data is reformatted and divided into 2 separated files: dataset1 and dataset2 for creating 2 different models (I've just kind of finished on the first one)
- the input data set (dataset1) is cleaned, reformatted and split into different sets: train, validation, test. Data is also standardized in the hope of increasing model performance
- in training stage model is created and train with the train dataset, then with models is tuned using a GridSearchCV to find best hyperparameters (alpha, l1_ratio)
- in validation stage different models are evaluated with validation dataset to find which provides best performance
- in test stage the best model in validation is evaluated 1 more time with test dataset
- in production stage a new model is build up with the full dataset.
While working with the models, i have some problems with models' performance.
And there are still some issue with dvc when i tried to use $ dvc repro -s with some stages.
If in terminal i run the command in cmd block of each stage, everything works. But issues occur if i use $ dvc repro -s

2022-11-12 10:22 UTC, LlirikOknessu commented
Still, I achieved good accuracy. See, it's really about normalization. You forget to normalize the output variable. In your code you just normalize all variables in X dataset and forget about y, because of that linear regression inadequately fits coefficients. Please do this and don't use ElasticNet with the parameters you have. They don't fit at all.
![image](https://user-images.githubusercontent.com/49691421/201469638-7062a1b7-c0b2-437e-af46-0ae959064f50.png)

2022-11-12 10:23 UTC, LlirikOknessu commented
I just add this line to your code and it works!)
![image](https://user-images.githubusercontent.com/49691421/201469815-9f1dc513-5f82-409e-8da9-5c34dd950b14.png)

2022-11-12 10:24 UTC, LlirikOknessu requested changes
See the other comments :)

2022-11-12 10:24 UTC, LlirikOknessu commented on .idea/LR.iml
> +<?xml version="1.0" encoding="UTF-8"?>
.idea убрать из коммита

2022-11-12 10:30 UTC, ACasualGuyFromDaLat commented
Thank you, I'll try again with normalization on Y datasets soon, at the moment still pretty busy with other subjects)

2022-11-16 14:02 UTC, LlirikOknessu approved these changes

2022-11-16 14:02 UTC, LlirikOknessu commented on requirementsVSCode.txt
> +matplotlib
Remove this file in the next pull request, please)

2022-11-16 14:02 UTC, LlirikOknessu commented on setupVSCode.txt
> +1. Clone repository
Remove this file in the next pull request, please)

2022-11-16 14:02 UTC, merged