Kushnarev v2
LlirikOknessu/LinearRegression pull request #11
Opened 2022-11-03 10:28 UTC by okushnarev

Hello! Check this brand new request please

2022-11-09 11:18 UTC, LlirikOknessu requested changes
Работа принимается, при условии, что пройдет мою валидацию. Пожалуйста, исправьте одно замечание и я приму)

2022-11-09 11:18 UTC, LlirikOknessu commented on Kushnarev/data/models/LinearRegression.csv
> +0,1,2,3,4,5,6,7
Пожалуйста, уберите промежуточные модели из коммита

2022-11-16 08:19 UTC, okushnarev commented on Kushnarev/data/models/LinearRegression.csv
> +0,1,2,3,4,5,6,7
Готово

2022-11-16 08:20 UTC, okushnarev commented
Successfully added decision tree files

2022-11-16 13:49 UTC, LlirikOknessu approved these changes
Я вижу, что все лучшие результаты достигнуты с максимальной глубиной в 7. Вы уеличить глубину пробовали? Потому что судя по всему ее недостаточно. Я вижу, что ваша ныняшеняя модель справляется немного лучше линейной регрессии. Укажите в отчете почему. Работу принимаю

2022-11-16 13:49 UTC, merged