KozlovaNA. Version with desion tree.
LlirikOknessu/LinearRegression pull request #14
Opened 2022-11-16 12:44 UTC by Darkvoyant

2022-11-16 14:30 UTC, LlirikOknessu commented on Kozlova/dvc.yaml
> +  decision_tree_validation:
Что-то тут с путями намудрен, исправьте, пожалуйста)
![image](https://user-images.githubusercontent.com/49691421/202207659-559e15da-d9e7-4fa2-81bb-4d835f2ca9b8.png)

2022-11-16 14:35 UTC, LlirikOknessu requested changes
Мою валидацию вы прошли. Исправьте проблемы в dvc пайплайне и я приму вашу работу

2022-11-27 09:09 UTC, Darkvoyant commented
Добавила XGBoosting и CatBoosting.

2022-12-14 12:23 UTC, LlirikOknessu approved these changes

2022-12-15 03:06 UTC, merged