Doan Quoc Toan
LlirikOknessu/LinearRegression pull request #27
Opened 2022-12-20 17:20 UTC by doanquoctoan0306

2022-12-23 12:51 UTC, LlirikOknessu requested changes
У меня есть сомнения о том не списана ли эта работа. В приложении скрин того, что в принципе вы шаг data_preparation в принципе не меняли, а взяли у своей одногруппницы. Анализ отличается, хоть и похожж но не существенно.
Если решили идти доконца, тогда вам нужно объяснить:
1. Исходя из чего и по какому принципу вы категоризизовывали признаки в самом начале анализа.
2. Каковы итоги анализа? Почему вы взяли те переменные, которые вы взяли и исходя из чего вы их взяли? Потому что пока складывается впечатления, что вы просто модифицировали код других.
![image](https://user-images.githubusercontent.com/49691421/209338909-073ae60d-e0fc-468c-abd8-e993c5b44fb4.png)

2022-12-23 12:51 UTC, LlirikOknessu commented on Doan/data/prepared/X_val.csv
> +1,0,0,1,1,40
Файлы с данными не добавляются в гит. Удалите, пожалуйста!

2022-12-23 21:15 UTC, doanquoctoan0306 commented on Doan/data/prepared/X_val.csv
> +1,0,0,1,1,40
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/36893575/209402043-2bb44928-4d34-4d97-969e-a6d6d7a101c6.png">

<img width="743" alt="image" src="https://user-images.githubusercontent.com/36893575/209404280-30c0e764-8e1d-4158-95c3-964a8bf6190d.png">


Я в начале построил график  heatmap, из результата выбрал категории, у которых есть коэффициенты не меньше 0.15. Как я написал описание на первой картине. 
И потом от каждой категории построил график зависимости послетестовой оценки от их и смотрел их зависимости. Если четко видеть зависимость, то я буду взять эту категорию. Вторая картина, это пример график и вывод зависимость послетестовой оценки от количества учащихся.
Переменные взял от выбранных категорий.

Теперь я по вашему коду в разделе демонстрации, переписал свой. 

Но если так не хорошо, и если вам удобно пожалуйста, дайте другие данные. Я буду с их переделать.

2023-01-14 05:31 UTC, LlirikOknessu requested changes
Не могу обновить вашу ветку у себя. Пожалуйста, удалите папку .dvc из гита (она не нужна). Так же проверьте, что нет ошибки в логах tensorboard
![image](https://user-images.githubusercontent.com/49691421/212457523-b729e6c7-9e12-41bf-a9b7-b75a7c6d32ab.png)

2023-01-14 08:25 UTC, LlirikOknessu reviewed
Все еще не могу скачать. Скорее всего из-за пути логов. Пожалуйста, не используйте в названиях папок  символы ":" и ",". Предположительно ошибка возникает из-за них
![image](https://user-images.githubusercontent.com/49691421/212463341-4d267a86-650a-4d57-b3e0-9060d198fdba.png)

2023-01-14 10:22 UTC, closed without merging