Ott grishechka
LlirikOknessu/LinearRegression pull request #4
Opened 2022-10-31 15:46 UTC by grigoriiott

Hi man! You'll see something incredible here. Waiting for your feedback.
With love, Grigoriiiiii

2022-11-08 09:16 UTC, LlirikOknessu requested changes
Устраните данные огрехи. Обязательные исправления: 
.idea не трогать
raw данные не удалять
прод версия модели должна присутствовать
Опцианальные, но будут влиять на конечные баллы. если не захотите исправлять (если так, то напишите в сообщении следующего Pull Request'а, что опциональные огрехи вы исправлять не собираетесь..
Также я видел беспорядок в анализе данных. Удалите оттуда часть измерения ошибки модели и оставьте только анализ. Также в анализе я не вижу никаких выводов по графикам и общего вывода. Не понимаю, почему именно так, а не иначе вы подготавливаете данные. Прошу, исправьте замечания,

2022-11-08 09:16 UTC, LlirikOknessu commented on .dvcignore
> +# https://dvc.org/doc/user-guide/dvcignore
Так, сразу говорю, что пушить изменения в папке .idea строго воспрещается (Изменения внизу). Убрать из Pull Request'а

2022-11-08 09:16 UTC, LlirikOknessu commented on Ott/data/raw/life_expectancy_data.csv
> -Country,Year,Status,Life expectancy ,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles , BMI ,under-five deaths ,Polio,Total expenditure,Diphtheria , HIV/AIDS,GDP,Popul
Почему исходный файл удален из ветки? Вернуть

2022-11-08 09:16 UTC, LlirikOknessu commented on Ott/liney_lineyich_prod.py
> +    dump(model, output_model_joblib_path)
Вижу, что вы сохраняли прод версию модели, но не закоммитили ее. Она должна быть в репозитории

2022-11-15 04:15 UTC, LlirikOknessu commented
Ну ну ну, не все готово. Все еще вижу файлы .idea в  pull request'е
![image](https://user-images.githubusercontent.com/49691421/201825038-22a4cfa7-b447-481f-a2c0-3a05906f952a.png)

2022-11-15 06:41 UTC, grigoriiott reviewed
Удалил все .idea

2022-11-16 13:31 UTC, LlirikOknessu commented
Перечитайте, пожалуйста ваши выводы в анализе и исправьте хотя бы ошибки. И то, что группировать страны по континентам долго - это не обоснование того, почему вы удалили эту колонку. Нужны статистические обоснования, а не трудоемкость. + стиль лучше бы научный сразу сделать потому что это в итоге должно пойти в отчет.
Также сделайте так, чтобы дерево и все цифры на картинке были различимы. В остальном все нормально. Как исправите указанные замечания - приму пулл реквест. Завтра можете приходить на защиту

2022-11-16 14:45 UTC, LlirikOknessu approved these changes

2022-11-16 14:46 UTC, merged