Kozlova Natalya
LlirikOknessu/LinearRegression pull request #6
Opened 2022-11-02 13:49 UTC by Darkvoyant

Maybe, this is a finished project and the best model ever (still probably).🐣
Looking forward to your feedback!😸

2022-11-09 09:39 UTC, LlirikOknessu requested changes
После того, как уберете промежуточные результаты (коэффициенты и файлы моделей не прод версии). Ваш пулл реквест будет принят. Хорошие выводы. Далле будет интересно наблюдать, как сработают другие алгоритмы машинного обучения на подготовленных вами данных :)

2022-11-09 09:39 UTC, LlirikOknessu commented on Kozlova/data/models/ElasticNet.csv
> +0
Промежуточные результаты, лучше не коммитить

2022-11-09 09:46 UTC, LlirikOknessu commented on Demonstration/Analysis.ipynb
>      "Data Scientist - это наиболее распространенная должность, за которой следуют Data Engineer и Data Analyst."
А и еще в Demonstration ничего не коммитеть!)

2022-11-09 12:43 UTC, Darkvoyant commented
Ух, изменять файлы в гите та еще морока, но я, вроде бы, справилась. Надеюсь, что теперь все верно! 🌞

2022-11-12 09:37 UTC, LlirikOknessu approved these changes
Только не dvs.yaml, а dvc.yaml) 
В следующий раз при работе dvc использовать!
В остальном, хорошая работа!)

2022-11-12 09:37 UTC, merged